# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gitgoblin < Formula
  desc "Terminal-based Git dashboard"
  homepage "https://github.com/Johannes-Berggren/gitgoblin"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Johannes-Berggren/gitgoblin/releases/download/v0.7.0/gitgoblin_0.7.0_darwin_amd64.tar.gz"
      sha256 "3665e4572543104d2af106bb53a55193d4f0c5c6aefae0bb451ab919c42e5e53"

      define_method(:install) do
        bin.install "goblin"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Johannes-Berggren/gitgoblin/releases/download/v0.7.0/gitgoblin_0.7.0_darwin_arm64.tar.gz"
      sha256 "57c507541c90ad30acf4991ed167fd01825e6ee10c19235a847c48b67d113ae8"

      define_method(:install) do
        bin.install "goblin"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Johannes-Berggren/gitgoblin/releases/download/v0.7.0/gitgoblin_0.7.0_linux_amd64.tar.gz"
      sha256 "272ef364d63443d622070491a7b463f321885611af5823de03cc55af3ab4af2a"
      define_method(:install) do
        bin.install "goblin"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Johannes-Berggren/gitgoblin/releases/download/v0.7.0/gitgoblin_0.7.0_linux_arm64.tar.gz"
      sha256 "95e929b9dff66ab484fddf9c50da9b9f2326732941ab2ca1cee97bb79b0acf80"
      define_method(:install) do
        bin.install "goblin"
      end
    end
  end

  test do
    system "#{bin}/goblin", "--help"
  end
end
