# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gitgoblin < Formula
  desc "A beautiful terminal-based Git dashboard"
  homepage "https://github.com/Johannes-Berggren/gitgoblin"
  version "0.5.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Johannes-Berggren/gitgoblin/releases/download/v0.5.0/gitgoblin_0.5.0_darwin_amd64.tar.gz"
      sha256 "cdda923a50b2ba2d9866023db1ceab687c4a1b45103953937031835ee26e8dfa"

      def install
        bin.install "goblin"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Johannes-Berggren/gitgoblin/releases/download/v0.5.0/gitgoblin_0.5.0_darwin_arm64.tar.gz"
      sha256 "9228d447031fb7098ce70153aa20a2f0914063939fe196ead5314d687a7e6819"

      def install
        bin.install "goblin"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Johannes-Berggren/gitgoblin/releases/download/v0.5.0/gitgoblin_0.5.0_linux_amd64.tar.gz"
      sha256 "807e6c15ca34afb5515450d9d65c7e829ea959f110f75d417e840d154cee899a"
      def install
        bin.install "goblin"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Johannes-Berggren/gitgoblin/releases/download/v0.5.0/gitgoblin_0.5.0_linux_arm64.tar.gz"
      sha256 "8a0053a958e226a77363a64d27eca79e9b2a6374be5cce24e5da6e98d67e4b1b"
      def install
        bin.install "goblin"
      end
    end
  end

  test do
    system "#{bin}/goblin", "--help"
  end
end
